const { onDocumentCreated, onDocumentWritten } = require('firebase-functions/v2/firestore')
const { onSchedule } = require('firebase-functions/v2/scheduler')
const admin = require('firebase-admin')
const { DateTime } = require('luxon')

admin.initializeApp()
const db = admin.firestore()
const messaging = admin.messaging()
const ZONE = 'America/Chicago'

const groupsFor = user => user.groups || (user.group ? [user.group] : [])
const tokenFor = user => user.fcmToken || null
const published = status => status === 'published' || status === 'submitted'

async function users() {
  const snap = await db.collection('users').get()
  return snap.docs.map(d => ({ id: d.id, ...d.data() }))
}

async function pushTo(userRows, title, body, data = {}) {
  const recipients = userRows.filter(u => tokenFor(u))
  if (!recipients.length) return
  await Promise.allSettled(recipients.map(u => messaging.send({
    token: tokenFor(u),
    // Data-only Web Push lets our service worker display exactly one system
    // notification and control where a tap opens in the installed PWA.
    data: Object.fromEntries(Object.entries({ title, body, ...data }).map(([k, v]) => [k, String(v)])),
    webpush: { headers: { Urgency: 'high' } },
  })))
}

function requiredSections(service, uid) {
  const s = service.sections || {}
  const out = []
  if ((s['Morning Worship'] || []).includes(uid)) out.push('Morning Worship')
  if ((s.Praise || []).includes(uid)) out.push('Praise')
  if ((s.Worship || []).includes(uid)) out.push('Worship')
  if ((s.Offering || []).includes(uid)) out.push('Offering')
  if ((s['Praise & Worship'] || []).includes(uid)) out.push('Praise', 'Worship')
  return [...new Set(out)]
}

exports.rehearsalCreatedPush = onDocumentCreated('rehearsals/{id}', async event => {
  const rehearsal = event.data?.data()
  if (!rehearsal || rehearsal.autoGenerated) return
  const all = await users()
  await pushTo(all, 'Rehearsal scheduled', `${rehearsal.name || 'Rehearsal'} · ${rehearsal.dateStr || ''}${rehearsal.time ? ` · ${rehearsal.time}` : ''}. Mark your availability.`, { tab: 'schedule', link: '/?tab=schedule' })
})

exports.rehearsalBatchCreatedPush = onDocumentCreated('notificationEvents/{id}', async event => {
  const batch = event.data?.data()
  if (!batch || batch.type !== 'rehearsal-batch-created') return
  const all = await users()
  const monthName = DateTime.fromObject({ year: Number(batch.year), month: Number(batch.month), day: 1 }, { zone: ZONE }).toFormat('LLLL')
  await pushTo(all, `${monthName} rehearsals are ready`, `${Number(batch.count) || 0} Saturday rehearsals were created. Mark your availability.`, { tab: 'schedule', link: '/?tab=schedule', tag: `rehearsals-${batch.year}-${batch.month}` })
})

exports.serviceCreatedPush = onDocumentCreated('services/{id}', async event => {
  const service = event.data?.data()
  if (!service) return
  const all = await users()
  await Promise.all(all.map(async u => {
    const assigned = requiredSections(service, u.id)
    const title = assigned.length ? 'You are assigned to an upcoming service' : 'Service scheduled'
    const body = assigned.length ? `${service.dateStr || 'Upcoming service'} · ${assigned.join(', ')}. Create your set list${assigned.length > 1 ? 's' : ''}.` : `${service.dateStr || 'Upcoming service'} has been added to the schedule.`
    await pushTo([u], title, body, {
      tab: 'schedule',
      serviceId: event.params.id,
      link: `/?tab=schedule&service=${event.params.id}`,
      tag: `service-${event.params.id}`,
    })
  }))
})

exports.setlistPublishedPush = onDocumentWritten('setlists/{id}', async event => {
  const before = event.data?.before?.exists ? event.data.before.data() : null
  const setlist = event.data?.after?.exists ? event.data.after.data() : null
  if (!setlist || !published(setlist.status) || published(before?.status)) return
  const all = (await users()).filter(u => u.id !== setlist.createdBy)
  await pushTo(all, 'New set list published', `${setlist.title || `${setlist.section} Set List`} · ${setlist.serviceDateStr || 'Upcoming service'}. View it now.`, { tab: 'setlist', setlistId: event.params.id, link: `/?tab=setlist&setlist=${event.params.id}`, tag: `setlist-${event.params.id}` })
})

exports.commsPostedPush = onDocumentCreated('messages/{id}', async event => {
  const msg = event.data?.data()
  if (!msg || msg.parentId) return
  const all = (await users()).filter(u => {
    if (u.id === msg.senderId) return false
    return msg.audience === 'all' || groupsFor(u).includes(msg.audience)
  })
  await pushTo(all, `New ${msg.audience === 'all' ? 'team' : msg.audience} message`, `${msg.senderName || 'Team member'}: ${String(msg.text || '').slice(0, 140)}`, { tab: 'comms', link: '/?tab=comms', tag: `comms-${event.params.id}` })
})

exports.midweekReminders = onSchedule({ schedule: '0 10 * * 3-5', timeZone: ZONE }, async () => {
  const now = DateTime.now().setZone(ZONE)
  const saturday = now.plus({ days: 6 - now.weekday }).startOf('day') // Luxon Mon=1 ... Sun=7
  const sunday = saturday.plus({ days: 1 })
  const all = await users()

  const rehSnap = await db.collection('rehearsals')
    .where('dateTs', '>=', saturday.toMillis())
    .where('dateTs', '<', saturday.plus({ days: 1 }).toMillis()).get()
  for (const d of rehSnap.docs) {
    const r = d.data()
    await Promise.all(all.map(async u => {
      const raw = r.rsvp?.[u.id]
      const submitted = typeof raw === 'string' ? !!raw : !!raw?.status
      if (!submitted) await pushTo([u], 'Rehearsal availability reminder', `Please submit your availability for ${r.name || 'Saturday rehearsal'}.`, { tab: 'schedule', link: '/?tab=schedule', tag: `rehearsal-reminder-${d.id}-${now.toISODate()}` })
    }))
  }

  const svcSnap = await db.collection('services')
    .where('dateTs', '>=', sunday.toMillis())
    .where('dateTs', '<', sunday.plus({ days: 1 }).toMillis()).get()
  for (const d of svcSnap.docs) {
    const service = { id: d.id, ...d.data() }
    const setSnap = await db.collection('setlists').where('serviceId', '==', service.id).get()
    const existing = new Set(setSnap.docs.map(x => x.data()).filter(x => published(x.status)).map(x => x.section))
    await Promise.all(all.map(async u => {
      const missing = requiredSections(service, u.id).filter(section => !existing.has(section))
      if (missing.length) await pushTo([u], 'Set list reminder', `You are assigned this Sunday and still need to publish: ${missing.join(', ')}.`, { tab: 'schedule', serviceId: service.id, link: `/?tab=schedule&service=${service.id}`, tag: `setlist-reminder-${service.id}-${now.toISODate()}` })
    }))
  }
})
