import { useEffect, useMemo, useState } from 'react'
import { collection, doc, onSnapshot, query, serverTimestamp, setDoc, writeBatch } from 'firebase/firestore'
import { db } from '../firebase'
import { useAuth } from '../contexts/AuthContext'
import { useServices } from './useServices'
import { useRehearsals } from './useRehearsals'
import { useSetlists } from './useSetlists'
import { useMessages } from './useMessages'

const published = status => status === 'published' || status === 'submitted'
const DAY = 24 * 60 * 60 * 1000
const UNREAD_RETENTION = 21 * DAY
const READ_RETENTION = 7 * DAY
const startOfDay = (value = new Date()) => { const d = new Date(value); d.setHours(0, 0, 0, 0); return d }
const dayKey = (value = new Date()) => {
  const d = new Date(value)
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
}
const tsMillis = value => value?.toMillis?.() || value?.toDate?.()?.getTime?.() || Number(value) || 0

function setlistSectionsForService(service, uid) {
  const sections = service?.sections || {}
  const required = []
  if ((sections['Morning Worship'] || []).includes(uid)) required.push('Morning Worship')
  if ((sections.Praise || []).includes(uid)) required.push('Praise')
  if ((sections.Worship || []).includes(uid)) required.push('Worship')
  if ((sections.Offering || []).includes(uid)) required.push('Offering')
  if ((sections['Praise & Worship'] || []).includes(uid)) required.push('Praise', 'Worship')
  return [...new Set(required)]
}

export function useNotifications() {
  const { user, profile } = useAuth()
  const { services } = useServices()
  const { rehearsals } = useRehearsals()
  const { setlists } = useSetlists()
  const { messages } = useMessages()
  const [readIds, setReadIds] = useState(new Set())

  useEffect(() => {
    if (!user) { setReadIds(new Set()); return undefined }
    const q = query(collection(db, 'users', user.uid, 'notificationReads'))
    return onSnapshot(q, snap => setReadIds(new Set(snap.docs.map(d => d.id))), err => {
      console.error('Notification read-state subscription failed:', err)
    })
  }, [user])

  const items = useMemo(() => {
    if (!user) return []
    const now = new Date()
    const nowMs = now.getTime()
    const today = startOfDay(now).getTime()
    const weekday = now.getDay()
    const groups = profile?.groups || (profile?.group ? [profile.group] : [])
    const out = []

    const automaticByMonth = new Map()
    rehearsals.forEach(r => {
      if ((r.dateTs || 0) < today) return
      if (r.autoGenerated) {
        const date = new Date(r.dateTs)
        const key = `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}`
        const batch = automaticByMonth.get(key) || []
        batch.push(r)
        automaticByMonth.set(key, batch)
        return
      }
      const createdAt = tsMillis(r.createdAt)
      if (!createdAt) return
      out.push({
        id: `rehearsal-created-${r.id}`,
        type: 'rehearsal',
        title: 'Rehearsal scheduled',
        body: `${r.name || 'Rehearsal'} · ${r.dateStr || ''}${r.time ? ` · ${r.time}` : ''}. Mark your availability.`,
        createdAt,
        tab: 'schedule',
      })
    })
    automaticByMonth.forEach((rows, key) => {
      rows.sort((a, b) => (a.dateTs || 0) - (b.dateTs || 0))
      const monthName = new Date(rows[0].dateTs).toLocaleDateString('en-US', { month: 'long', timeZone: 'UTC' })
      const createdTimes = rows.map(r => tsMillis(r.createdAt)).filter(Boolean)
      if (!createdTimes.length) return
      out.push({
        id: `rehearsals-created-${key}`,
        type: 'rehearsal',
        title: `${monthName} rehearsals are ready`,
        body: `${rows.length} Saturday rehearsal${rows.length === 1 ? '' : 's'} were created. Mark your availability.`,
        createdAt: Math.max(...createdTimes),
        tab: 'schedule',
      })
    })

    services.forEach(s => {
      if ((s.dateTs || 0) < today) return
      const assigned = setlistSectionsForService(s, user.uid)
      const createdAt = tsMillis(s.createdAt)
      if (!createdAt) return
      out.push({
        id: `service-created-${s.id}`,
        type: 'service',
        title: assigned.length ? 'You are assigned to an upcoming service' : 'Service scheduled',
        body: assigned.length
          ? `${s.dateStr || 'Upcoming service'} · ${assigned.join(', ')}. Create the needed set list${assigned.length > 1 ? 's' : ''}.`
          : `${s.dateStr || 'Upcoming service'} has been added to the schedule.`,
        createdAt,
        tab: 'schedule',
        serviceId: s.id,
      })
    })

    setlists.filter(s => published(s.status) && s.createdBy !== user.uid && (s.serviceDateTs || 0) >= today).forEach(s => {
      out.push({
        id: `setlist-published-${s.id}`,
        type: 'setlist',
        title: 'New set list published',
        body: `${s.title || `${s.section} Set List`} · ${s.serviceDateStr || 'Upcoming service'}. View it now.`,
        createdAt: tsMillis(s.submittedAt) || tsMillis(s.updatedAt) || tsMillis(s.createdAt),
        tab: 'setlist', setlistId: s.id,
      })
    })

    messages.forEach(m => {
      const relevant = m.senderId !== user.uid && (m.audience === 'all' || groups.includes(m.audience))
      if (!relevant) return
      out.push({
        id: `comms-${m.id}`,
        type: 'comms',
        title: `New ${m.audience === 'all' ? 'team' : m.audience} message`,
        body: `${m.senderName || 'Team member'}: ${String(m.text || '').slice(0, 120)}`,
        createdAt: tsMillis(m.createdAt),
        tab: 'comms',
      })
    })

    if (weekday >= 3 && weekday <= 5) {
      const saturdayOffset = 6 - weekday
      const sundayOffset = 7 - weekday
      const saturday = new Date(now); saturday.setHours(0,0,0,0); saturday.setDate(saturday.getDate() + saturdayOffset)
      const sunday = new Date(now); sunday.setHours(0,0,0,0); sunday.setDate(sunday.getDate() + sundayOffset)

      rehearsals.filter(r => startOfDay(r.dateTs).getTime() === saturday.getTime()).forEach(r => {
        const raw = r.rsvp?.[user.uid]
        const submitted = typeof raw === 'string' ? !!raw : !!raw?.status
        if (!submitted) out.push({
          id: `attendance-reminder-${r.id}-${dayKey(now)}`,
          type: 'reminder',
          title: 'Rehearsal availability reminder',
          body: `You have not submitted availability for ${r.name || 'Saturday rehearsal'}. Please respond before it closes.`,
          createdAt: nowMs, tab: 'schedule',
        })
      })

      services.filter(s => startOfDay(s.dateTs).getTime() === sunday.getTime()).forEach(s => {
        const required = setlistSectionsForService(s, user.uid)
        const missing = required.filter(section => !setlists.some(x => published(x.status) && x.serviceId === s.id && x.section === section))
        if (missing.length) out.push({
          id: `setlist-reminder-${s.id}-${dayKey(now)}`,
          type: 'reminder',
          title: 'Set list reminder',
          body: `You are assigned this Sunday and still need to publish: ${missing.join(', ')}.`,
          createdAt: nowMs, tab: 'schedule', serviceId: s.id,
        })
      })
    }

    return out
      .map(item => ({ ...item, read: readIds.has(item.id) }))
      // Notification center is intentionally short-lived. Read items disappear
      // after 7 days; unread items expire after 21 days so the bell never becomes
      // an archive of every event the app has ever generated.
      .filter(item => {
        const age = nowMs - Number(item.createdAt || nowMs)
        return age <= (item.read ? READ_RETENTION : UNREAD_RETENTION)
      })
      .sort((a, b) => Number(b.createdAt || 0) - Number(a.createdAt || 0))
      .slice(0, 40)
  }, [messages, profile, readIds, rehearsals, services, setlists, user])

  const markRead = async id => {
    if (!user || !id || readIds.has(id)) return
    setReadIds(current => new Set([...current, id]))
    try {
      await setDoc(doc(db, 'users', user.uid, 'notificationReads', id), { readAt: serverTimestamp() }, { merge: true })
    } catch (error) {
      console.error('Could not mark notification as read:', error)
      setReadIds(current => {
        const next = new Set(current)
        next.delete(id)
        return next
      })
      throw error
    }
  }

  const markAllRead = async () => {
    if (!user) return
    const unread = items.filter(item => !item.read)
    if (!unread.length) return
    const ids = unread.map(item => item.id)
    setReadIds(current => new Set([...current, ...ids]))
    try {
      // Firestore batches are limited to 500 writes; the notification center is
      // capped at 40, so this remains safely atomic for the visible list.
      const batch = writeBatch(db)
      unread.forEach(item => batch.set(
        doc(db, 'users', user.uid, 'notificationReads', item.id),
        { readAt: serverTimestamp() },
        { merge: true },
      ))
      await batch.commit()
    } catch (error) {
      console.error('Could not mark all notifications as read:', error)
      setReadIds(current => {
        const next = new Set(current)
        ids.forEach(id => next.delete(id))
        return next
      })
      throw error
    }
  }

  return { notifications: items, unreadCount: items.filter(item => !item.read).length, markRead, markAllRead }
}
