import config from '../config'

// Parse a hex colour into [r, g, b] for jsPDF
function hexToRgb(hex) {
  const h = hex.replace('#', '')
  return [parseInt(h.slice(0,2),16), parseInt(h.slice(2,4),16), parseInt(h.slice(4,6),16)]
}

// Export a setlist (array of pills) as a formatted PDF using jsPDF
export async function exportSetlistPDF(eventName, pills, songs) {
  const { default: jsPDFModule } = await import('jspdf')
  const jsPDF = jsPDFModule.jsPDF || jsPDFModule
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  const W = doc.internal.pageSize.getWidth()
  const MARGIN = 20

  // Header
  doc.setFillColor(...hexToRgb(config.accentColor))
  doc.rect(0, 0, W, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text(config.orgName, MARGIN, 12)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text(`Setlist — ${eventName}`, MARGIN, 20)

  // Date
  const dateStr = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
  doc.setFontSize(9)
  doc.text(dateStr, W - MARGIN, 20, { align: 'right' })

  let y = 40
  doc.setTextColor(0, 0, 0)

  const PILL_COLORS = {
    song:       [232, 240, 254],
    interlude:  [255, 243, 224],
    prayer:     [240, 232, 254],
    transition: [232, 249, 238],
  }
  const PILL_TEXT = {
    song:       [26, 86, 219],
    interlude:  [180, 83, 9],
    prayer:     [124, 58, 237],
    transition: [26, 127, 55],
  }

  pills.forEach((pill, idx) => {
    if (y > 260) { doc.addPage(); y = 20 }

    // Numbered row background
    doc.setFillColor(248, 248, 250)
    doc.roundedRect(MARGIN, y - 5, W - MARGIN * 2, 18, 3, 3, 'F')

    // Sequence number
    doc.setFillColor(...PILL_COLORS[pill.type] || PILL_COLORS.song)
    doc.roundedRect(MARGIN + 2, y - 3, 8, 14, 2, 2, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(...PILL_TEXT[pill.type] || PILL_TEXT.song)
    doc.text(`${idx + 1}`, MARGIN + 6, y + 5, { align: 'center' })

    // Title
    doc.setTextColor(0, 0, 0)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.text(pill.label, MARGIN + 14, y + 5)

    // Song details if type is song
    if (pill.type === 'song') {
      const song = songs?.find(s => s.id === pill.id)
      if (song) {
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(9)
        doc.setTextColor(100, 100, 100)
        doc.text(`Key: ${song.key} · ${song.bpm} BPM`, W - MARGIN - 2, y + 5, { align: 'right' })
      }
    }

    y += 22
  })

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text(`Generated by ${config.orgName} · Band Manager`, MARGIN, 285)
  doc.text(`${pills.length} items`, W - MARGIN, 285, { align: 'right' })

  doc.save(`setlist-${eventName.replace(/\s+/g, '-').toLowerCase()}.pdf`)
}
